### ISSUE TITLE
获取不到解析内容

### ISSUE THREAD

**Issue by RedSevenMale** [debuggerx01/JSONFormat4Flutter#14]
![image](https://user-images.githubusercontent.com/39144187/48596680-19f9cb80-e995-11e8-90fc-c8d3ced04b9d.png)
获取data里面有数据，用这个FollowList followList = new FollowList(data);，解析不了是什么原因

**Comment by debuggerx01** [comment]
@RedSevenMale 你这个接口返回的JSON对象有点怪，结果是JSON对象里有一个叫做'data'的字段，这个字段的值才是你真正想要的数据。
看你的调试截图，这里得到的data已经是去掉顶层对象后data的值了，而你转换出的FollowList这个模板类却应该接收一个没有去掉顶层数据的完整JSON对象，所以要么修改你NetUtil.get的逻辑不要提前取出data属性，要么把生成对象的代码改成new Data.fromJSON(data);这种方式。
