### ISSUE TITLE
大佬能否支持 下面2个功能1.支持字段驼峰 2.解析List的时候是否可以读取多个元素（默认是第一个，可能第一个数据字段不全）

### ISSUE THREAD

**Issue by zmtzawqlp** [debuggerx01/JSONFormat4Flutter#17]
大佬能否支持 下面2个功能
1.支持字段驼峰 
2.解析List的时候是否可以读取多个数据（默认是解析的是第一个，但是可能第一个数据字段不全）

**Comment by debuggerx01** [comment]
@zmtzawqlp 可以试试dev分支是不是满足需求了

**Comment by zmtzawqlp** [comment]
大佬威武。。谢谢大佬。我看看呢

**Comment by zmtzawqlp** [comment]
> @zmtzawqlp 可以试试dev分支是不是满足需求了

大佬。。不好意思。。那个我没运行你代码的环境。。能帮忙打个windows 下面的release 包吗。。谢谢
