### ISSUE TITLE
无法生成Bean

### ISSUE THREAD

**Issue by lionoggo** [debuggerx01/JSONFormat4Flutter#22]
![image](https://user-images.githubusercontent.com/5570323/54267249-debe8080-45b3-11e9-8e2f-1a2433faca1b.png)

**Comment by HYAdonisCoding** [comment]
我也遇到这问题了。
<img width="927" alt="WX20190830-163927@2x" src="https://user-images.githubusercontent.com/17538734/64006425-e31c2d00-cb44-11e9-96a0-21b9f26cc3a9.png">

**Comment by debuggerx01** [comment]
@lionoggo @HYAdonisCoding 
这是正常的 第一个框需要输入实体类的类名，你们从下拉框勾选了"Object"(老版本)"Map<String, dynamic>"(新版本)的意思就是忽略了整个json的解析 所以生成的代码就是空白
Oject/Map的选项只是用来处理json中某个对象的属性是动态的，需要忽略解析原样返回的情况
