### ISSUE TITLE
json本身的顶层级不是对象而是数组，解析报错

### ISSUE THREAD

**Issue by kamike** [debuggerx01/JSONFormat4Flutter#28]
![image](https://user-images.githubusercontent.com/3920019/83723180-d0ed9300-a670-11ea-9f17-5d0f7eaa213b.png)

[{"a":"xx","b":"bbb"},{"a":"xx","b":"bbbb"},{"a":"xx","b":"bbbbb"}]

![image](https://user-images.githubusercontent.com/3920019/83723317-14480180-a671-11ea-861d-5c2db41eeb30.png)

dui对于这种整个json就是一个数组的，设置的没问题，解析报错
type 'String' is not a subtype of type 'int' of 'index'

我看了下，生成的代码jsonRes['json_list']，这里明显有问题，json_list这个key是不存在的，所以报错了

![image](https://user-images.githubusercontent.com/3920019/83723345-1f9b2d00-a671-11ea-9147-b460cf23af1f.png)

个人感觉对于这种类型，直接当做数组item的json来处理，额外再提供一下数组解析的方法就好了

**Comment by kamike** [comment]
如果要解析列表就要添加类似这样的一个方法
static List<AddressInfoModel>  fromJsonList(String jsonStr) {
    List listJson = json.decode(jsonStr);
    List<AddressInfoModel> list = List<AddressInfoModel>();
    for (var item in listJson) {
      list.add(AddressInfoModel.fromJson(item));
    }
    return list;
  }

**Comment by debuggerx01** [comment]
[Release 0.8](https://github.com/debuggerx01/JSONFormat4Flutter/releases/tag/0.8)

**Comment by kamike** [comment]
666
