### ISSUE TITLE
关于生成class的构造函数的疑问

### ISSUE THREAD

**Issue by jianmu297** [debuggerx01/JSONFormat4Flutter#5]
发现生成的class中只有一个带参的构造函数，如果我不直接传jsonStr进去，而是想初始化一个空的class。给class一个默认构造函数，给转换构造函数加一个命名是不是更好？

**Json**

`{
    "name": "BeJson",
    "email": "http://www.bejson.com",
    "list": [
        "Google",
        "baidu",
        "facebook"
    ]
}`

**Class，嵌套class以此类推**
```
  class UserModel {

  String email;
  String name;
  List<String> list;

  UserModel(){
    list = [];
  }

  UserModel.byJson(jsonStr) {
  var jsonRes = json.decode(jsonStr);

    email = jsonRes['email'];
    name = jsonRes['name'];
    list = [];

  for (var listItem in jsonRes['list']){
    
      list.add(listItem);
    }
  }
```
初学dart，语法还不太熟，请见谅

**Comment by debuggerx01** [comment]
还是按照之前讨论时我构思的方式，对构造模板进行了修改，具体内容在提交信息中，可以的话更新下跑跑看有没有什么问题，没问题我就打包发布版本了
@jianmu297
