### ISSUE TITLE
IDEA plugin 

### ISSUE THREAD

**Issue by zhangkangbin** [debuggerx01/JSONFormat4Flutter#9]
怎么不把这个搞成  IDEA plugin 呢，这样不就方便很多了嘛。

**Comment by debuggerx01** [comment]
我没有写成插件的计划。以前写过简单的IDEA插件，还是挺麻烦的，而且只能用java/kotlin写，没法复用代码给vscode用，所以选择了可以打包三个桌面平台的PyQt来写这个工具，写起来快，维护也比写两份插件来得方便。
如果是觉得使用不如插件来得方便，可以参考下面的gif把工具设置为IDE的外部工具，这样就可以在IDE里快速启动了(vscode也可以通过配置自定义命令实现类似效果)：


![_desktop_20180706174243](https://user-images.githubusercontent.com/19624835/42372811-d61eeaf6-8145-11e8-84b4-fdad318f5957.gif)
